export const categories=[['all','كل الأدوات'],['organize','تنظيم الصفحات'],['convert','التحويلات'],['edit','التعديل والتوقيع'],['optimize','الضغط والتحسين'],['security','الحماية'],['extra','أدوات إضافية']];
// id, title, description, category, icon, accent, input, options
export const tools=[
['merge','دمج PDF','اجمع ملفاتك في ملف واحد بالترتيب اللي تختاره.','organize','Layers','coral','pdf'],
['split','تقسيم PDF','افصل كل صفحة أو قسّم الملف إلى نطاقات.','organize','Scissors','blue','pdf'],
['compress','ضغط PDF','قلّل الحجم مع اختيار جودة الصور المناسبة.','optimize','Minimize2','green','pdf'],
['pdf-word','PDF إلى Word','استخرج النصوص في مستند Word قابل للتعديل.','convert','FileText','blue','pdf'],
['word-pdf','Word إلى PDF','حوّل ملفات DOCX إلى صفحات PDF.','convert','FileInput','blue','docx'],
['pdf-images','PDF إلى صور','احفظ الصفحات بصيغة JPG أو PNG في ملف ZIP.','convert','Image','amber','pdf'],
['images-pdf','صور إلى PDF','اجمع صور JPG وPNG وWebP في مستند واحد.','convert','Images','amber','image'],
['pdf-excel','PDF إلى Excel','استخرج سطور النص إلى جدول Excel.','convert','Sheet','green','pdf'],
['excel-pdf','Excel إلى PDF','حوّل أوراق العمل إلى PDF قابل للمشاركة.','convert','FileSpreadsheet','green','excel'],
['pdf-ppt','PDF إلى PowerPoint','حوّل كل صفحة إلى شريحة مصورة.','convert','Presentation','coral','pdf'],
['ppt-pdf','PowerPoint إلى PDF','استخرج نصوص وصور شرائح PPTX إلى PDF.','convert','GalleryHorizontalEnd','coral','pptx'],
['rotate','تدوير PDF','عدّل اتجاه الصفحات بزاوية 90 أو 180 درجة.','organize','RotateCw','purple','pdf'],
['organize','ترتيب الصفحات','رتّب الصفحات، كرّرها، أو احذف اللي مش محتاجه.','organize','LayoutGrid','coral','pdf'],
['extract','استخراج صفحات','احتفظ بصفحات محددة في ملف جديد.','organize','Files','purple','pdf'],
['remove','حذف صفحات','شيل صفحات محددة مع الاحتفاظ بالباقي.','organize','Trash2','coral','pdf'],
['watermark','علامة مائية','أضف نصًا عربيًا أو إنجليزيًا على كل صفحة.','edit','Stamp','purple','pdf'],
['numbers','ترقيم الصفحات','أضف أرقام الصفحات في المكان اللي تختاره.','edit','ListOrdered','blue','pdf'],
['edit','إضافة نص وصورة','أضف ملاحظة أو صورة إلى صفحة محددة.','edit','Pencil','green','pdf'],
['sign','توقيع PDF','ارسم توقيعك وأضفه إلى المستند.','edit','PenLine','purple','pdf'],
['crop','قص الهوامش','قلّل الهوامش الظاهرة لكل صفحات المستند.','edit','Crop','amber','pdf'],
['redact','حجب معلومات','احذف منطقة حساسة بتحويل الصفحة إلى صورة.','security','ScanLine','coral','pdf'],
['protect','حماية بكلمة مرور','شفّر مستندك بكلمة مرور باستخدام AES.','security','LockKeyhole','green','pdf'],
['unlock','فتح PDF','افتح مستندًا محميًا باستخدام كلمة مروره.','security','UnlockKeyhole','green','pdf'],
['forms','تعبئة النماذج','املأ حقول النص ومربعات الاختيار الموجودة.','edit','ClipboardList','blue','pdf'],
['autofill','تعبئة بيانات تلقائية','اسحب البيانات من ملف واملأ نموذج Word أو PDF تلقائيًا مع معاينة.','extra','FileInput','blue','autofill'],
['ocr','استخراج نص من الصور','تعرّف على النص العربي والإنجليزي من صور أو PDF.','extra','ScanText','purple','ocr'],
['text','PDF إلى نص','استخرج النصوص في ملف TXT أو Markdown.','convert','Text','blue','pdf'],
['html-pdf','نص وHTML إلى PDF','أنشئ PDF من نص أو محتوى HTML.','convert','CodeXml','amber','html'],
['scan','مسح مستند','صوّر بالموبايل وحوّل الصور إلى PDF.','extra','Camera','green','image'],
['compare','مقارنة ملفين','قارن النصوص صفحة بصفحة وحدّد الاختلافات.','extra','GitCompareArrows','purple','pdf'],
['grayscale','أبيض وأسود','حوّل الصفحات إلى تدرجات رمادية للطباعة.','optimize','Contrast','green','pdf'],
['repair','إعادة بناء PDF','أعد حفظ ملف قابل للقراءة لتنظيف بنيته.','optimize','Wrench','amber','pdf'],
['metadata','بيانات المستند','غيّر العنوان والمؤلف والكلمات المفتاحية.','extra','Info','blue','pdf'],
['flatten','تثبيت حقول النموذج','حوّل بيانات النموذج إلى محتوى ثابت.','extra','CopyCheck','green','pdf'],
['pdfa','PDF إلى PDF/A','نسخة أرشيفية طويلة الأجل — تتطلب خدمة التحويل.','convert','Archive','green','pdf'],
['searchable','PDF قابل للبحث','أضف طبقة OCR قابلة للبحث — تتطلب خدمة التحويل.','extra','ScanSearch','purple','pdf'],
['summarize','تلخيص PDF','ملخص عربي للنص — يتطلب تفعيل خدمة الذكاء الاصطناعي.','extra','Sparkles','purple','pdf'],
['translate','ترجمة PDF','ترجمة النص المستخرج — تتطلب تفعيل خدمة الذكاء الاصطناعي.','extra','Languages','blue','pdf'],
['blank','إنشاء PDF فارغ','أنشئ مستند A4 بعدد الصفحات اللي تحتاجه.','extra','FilePlus2','blue','none'],
['image-tools','ضغط وتحويل الصور','غيّر الحجم والصيغة والجودة في خطوة واحدة.','extra','Sparkles','amber','image'],
['workflow','سلسلة أدوات','ادمج ثم دوّر ورقّم الملفات في عملية واحدة.','extra','Workflow','purple','pdf'],
].map(([id,title,description,category,icon,color,input])=>({id,title,description,category,icon,color,input}));
