import { PDFDocument } from 'pdf-lib';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import JSZip from 'jszip';
import { loadPdf,mergeFiles,selectPages,pageRange,rotatePages,numberPages,safeName } from './engine.js';
pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
export async function readVisual(file,password){return pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),password,cMapUrl:'/cmaps/',cMapPacked:true,standardFontDataUrl:'/standard_fonts/',wasmUrl:'/wasm/'}).promise;}
export async function renderPage(doc,index,scale=1.5){const p=await doc.getPage(index+1);const v=p.getViewport({scale});const c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return c;}
async function extractText(file){const d=await readVisual(file);try{const pages=[];for(let i=1;i<=d.numPages;i++){const content=await(await d.getPage(i)).getTextContent();let lines=[],line='';for(const item of content.items){line+=item.str+' ';if(item.hasEOL){lines.push(line.trim());line='';}}if(line.trim())lines.push(line.trim());pages.push(lines.join('\n'));}return pages;}finally{await d.destroy();}}
const pdfResult=async(d,name='BDF-Egypt.pdf')=>[{data:await d.save(),name,type:'application/pdf'}];
const canvasBlob=(c,type='image/jpeg',quality=.85)=>new Promise(resolve=>c.toBlob(resolve,type,quality));
async function stampText(doc,text,opts={}){const c=document.createElement('canvas');const ctx=c.getContext('2d');c.width=1600;c.height=160;ctx.font='bold 64px Arial';ctx.textAlign='center';ctx.fillStyle=opts.color||'#087d75';ctx.direction='rtl';ctx.fillText(text,c.width/2,105);const im=await doc.embedPng(await(await canvasBlob(c,'image/png')).arrayBuffer());for(const p of doc.getPages()){const w=Math.min(p.getWidth()*.75,500),h=w*.1;p.drawImage(im,{x:(p.getWidth()-w)/2,y:opts.y??p.getHeight()/2,width:w,height:h,opacity:opts.opacity??.25});}}
async function imagesPdf(files,o){const d=await PDFDocument.create();for(const file of files){const bitmap=await createImageBitmap(file);const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;c.getContext('2d').drawImage(bitmap,0,0);bitmap.close();const im=await d.embedJpg(await(await canvasBlob(c)).arrayBuffer());const landscape=o.orientation==='landscape';const w=landscape?842:595,h=landscape?595:842,m=Number(o.margin||20);const scale=Math.min((w-2*m)/im.width,(h-2*m)/im.height);const p=d.addPage([w,h]);p.drawImage(im,{x:(w-im.width*scale)/2,y:(h-im.height*scale)/2,width:im.width*scale,height:im.height*scale});}return d;}
async function rasterPdf(file,o,progress,redact=false){const src=await readVisual(file);const out=await PDFDocument.create();try{for(let i=0;i<src.numPages;i++){progress(Math.round((i/src.numPages)*90));const c=await renderPage(src,i,Number(o.scale||1.25));const ctx=c.getContext('2d');if(o.grayscale){const a=ctx.getImageData(0,0,c.width,c.height);for(let n=0;n<a.data.length;n+=4){const g=a.data[n]*.299+a.data[n+1]*.587+a.data[n+2]*.114;a.data[n]=a.data[n+1]=a.data[n+2]=g;}ctx.putImageData(a,0,0);}
 if(redact&&i===Number(o.page||1)-1){ctx.fillStyle='#000';ctx.fillRect(c.width*Number(o.x)/100,c.height*Number(o.y)/100,c.width*Number(o.width)/100,c.height*Number(o.height)/100);}
 const original=(await src.getPage(i+1)).getViewport({scale:1});const im=await out.embedJpg(await(await canvasBlob(c,'image/jpeg',Number(o.quality||.75))).arrayBuffer());out.addPage([original.width,original.height]).drawImage(im,{x:0,y:0,width:original.width,height:original.height});}return out;}finally{await src.destroy();}}
async function htmlPdf(html){const [{default:DOMPurify},{default:html2canvas}]=await Promise.all([import('dompurify'),import('html2canvas')]);const holder=document.createElement('div');holder.style.cssText='position:absolute;left:-10000px;top:0;width:760px;background:white;color:#111;padding:36px;font:18px Arial;line-height:1.8;direction:rtl;overflow-wrap:anywhere;';holder.innerHTML=DOMPurify.sanitize(html,{FORBID_TAGS:['script','iframe','object','embed','style','link','form'],FORBID_ATTR:['srcset','style']});holder.querySelectorAll('img').forEach(im=>{if(!im.src.startsWith('data:'))im.remove();else im.style.maxWidth='100%';});holder.querySelectorAll('table').forEach(t=>{t.style.borderCollapse='collapse';t.style.width='100%';});holder.querySelectorAll('td,th').forEach(t=>t.style.cssText='border:1px solid #ddd;padding:8px;');document.body.append(holder);try{const canvas=await html2canvas(holder,{scale:1.5,backgroundColor:'#ffffff',logging:false});const d=await PDFDocument.create();const pageHeight=Math.floor(canvas.width*842/595);for(let y=0;y<canvas.height;y+=pageHeight){const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=pageHeight;const ctx=slice.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,slice.width,slice.height);ctx.drawImage(canvas,0,y,canvas.width,Math.min(pageHeight,canvas.height-y),0,0,canvas.width,Math.min(pageHeight,canvas.height-y));const im=await d.embedJpg(await(await canvasBlob(slice,'image/jpeg',.92)).arrayBuffer());d.addPage([595,842]).drawImage(im,{x:0,y:0,width:595,height:842});}return d;}finally{holder.remove();}}
export async function execute(id,files,o,progress=()=>{},signature){
const base=files[0]?safeName(files[0].name.replace(/\.[^.]+$/,'')):'BDF-Egypt';progress(5);
if(id==='blank'){const d=await PDFDocument.create();for(let i=0;i<Number(o.count||1);i++)d.addPage([595,842]);return pdfResult(d);}
if(id==='html-pdf'){let html=o.html||'';if(files[0])html=await files[0].text();if(!html.trim())throw Error('أضف النص أو محتوى HTML أولًا.');return pdfResult(await htmlPdf(html));}
if(!files.length)throw Error('اختر ملفًا أولًا.');
if(['pdfa','searchable','summarize','translate'].includes(id))return advanced(id,files[0],o);
if(['protect','unlock'].includes(id)){if(!o.password||id==='protect'&&o.password.length<6)throw Error('اكتب كلمة مرور؛ للحماية استخدم 6 أحرف على الأقل.');if(files[0].size>2.8*1024*1024)throw Error('الحد الحالي للحماية وفتح الملفات 2.8 MB. باقي الأدوات تعمل محليًا.');const bytes=new Uint8Array(await files[0].arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const response=await fetch('/api/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:id,password:o.password,file:btoa(binary)})});const data=await response.json().catch(()=>({error:'خدمة الحماية غير متاحة. جرّب مرة أخرى.'}));if(!response.ok)throw Error(data.error||'فشلت العملية.');return [{data:Uint8Array.from(atob(data.file),c=>c.charCodeAt(0)),name:base+'-'+id+'.pdf',type:'application/pdf'}];}
if(['merge','workflow'].includes(id)){if(files.length<2)throw Error('اختر ملفين PDF على الأقل.');const d=await mergeFiles(files);if(id==='workflow'){rotatePages(d,o.rotation||0);if(o.numbering==='yes')await numberPages(d);}return pdfResult(d,'BDF-Egypt-merged.pdf');}
if(['images-pdf','scan'].includes(id))return pdfResult(await imagesPdf(files,o),base+'.pdf');
if(id==='image-tools'){const z=new JSZip();for(let i=0;i<files.length;i++){const im=await createImageBitmap(files[i]);const ratio=Math.min(1,Number(o.maxWidth||1600)/im.width);const c=document.createElement('canvas');c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);const ctx=c.getContext('2d');if(o.format!=='png'){ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);}ctx.drawImage(im,0,0,c.width,c.height);im.close();const ext=o.format||'jpg';z.file(`${i+1}-${safeName(files[i].name.replace(/\.[^.]+$/,''))}.${ext}`,await canvasBlob(c,ext==='jpg'?'image/jpeg':'image/'+ext,Number(o.quality||.85)));}return[{data:await z.generateAsync({type:'uint8array'}),name:'BDF-Egypt-images.zip',type:'application/zip'}];}
if(id==='word-pdf'){const mammoth=await import('mammoth');const r=await mammoth.convertToHtml({arrayBuffer:await files[0].arrayBuffer()});return pdfResult(await htmlPdf(r.value),base+'.pdf');}
if(id==='excel-pdf'){const XLSX=await import('xlsx');const book=XLSX.read(await files[0].arrayBuffer());if(book.SheetNames.length>30)throw Error('الحد الحالي 30 ورقة عمل.');let html='';for(const name of book.SheetNames){const sh=book.Sheets[name];const range=XLSX.utils.decode_range(sh['!ref']||'A1');if(range.e.r>2000||range.e.c>40)throw Error('قلّل الجدول إلى 2000 صف و40 عمود قبل التحويل.');html+='<h2>'+escapeHtml(name)+'</h2>'+XLSX.utils.sheet_to_html(sh);}return pdfResult(await htmlPdf(html),base+'.pdf');}
if(id==='ppt-pdf'){const zip=await JSZip.loadAsync(await files[0].arrayBuffer());const paths=Object.keys(zip.files).filter(p=>/^ppt\/slides\/slide\d+\.xml$/.test(p)).sort((a,b)=>Number(a.match(/slide(\d+)/)[1])-Number(b.match(/slide(\d+)/)[1]));let out=await PDFDocument.create();for(const path of paths){const xml=new DOMParser().parseFromString(await zip.file(path).async('string'),'text/xml');const texts=[...xml.getElementsByTagName('a:t')].map(n=>n.textContent);let html='<h2>شريحة '+(paths.indexOf(path)+1)+'</h2>'+texts.map(t=>'<p>'+escapeHtml(t)+'</p>').join('');const relPath=path.replace('slides/','slides/_rels/')+'.rels';if(zip.file(relPath)){const rels=new DOMParser().parseFromString(await zip.file(relPath).async('string'),'text/xml');for(const rel of rels.getElementsByTagName('Relationship')){if(!rel.getAttribute('Type')?.endsWith('/image'))continue;const target=rel.getAttribute('Target');const mediaPath=target?.startsWith('../media/')?'ppt/media/'+target.slice(9):null;if(!mediaPath||!zip.file(mediaPath)||!/\.(png|jpe?g)$/i.test(mediaPath))continue;const ext=mediaPath.endsWith('.png')?'png':'jpeg';html+=`<img src="data:image/${ext};base64,${await zip.file(mediaPath).async('base64')}">`;}}const d=await htmlPdf(html);(await out.copyPages(d,d.getPageIndices())).forEach(p=>out.addPage(p));}if(!paths.length)throw Error('لم يتم العثور على شرائح PPTX.');return pdfResult(out,base+'.pdf');}
if(['text','pdf-word','pdf-excel','compare'].includes(id)){const texts=await extractText(files[0]);if(id!=='compare'&&!texts.some(t=>t.trim()))throw Error('الملف مصوّر ولا يحتوي نصًا. استخدم أداة OCR.');if(id==='text')return[{data:texts.map((t,i)=>o.format==='md'?`## صفحة ${i+1}\n\n${t}`:t).join('\n\n'),name:base+'.'+(o.format==='md'?'md':'txt'),type:'text/plain;charset=utf-8'}];if(id==='pdf-word'){const {Document,Packer,Paragraph,TextRun}=await import('docx');const doc=new Document({sections:[{children:texts.flatMap((t,i)=>[new Paragraph({text:`صفحة ${i+1}`,heading:'Heading1'}),...t.split('\n').map(line=>new Paragraph({bidirectional:/[\u0600-\u06ff]/.test(line),children:[new TextRun(line)]}))])}]});return[{data:await Packer.toBlob(doc),name:base+'.docx',type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}];}if(id==='pdf-excel'){const XLSX=await import('xlsx');const book=XLSX.utils.book_new();texts.forEach((t,i)=>XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(t.split('\n').map((line,n)=>[n+1,line])),'Page '+(i+1)));return[{data:XLSX.write(book,{type:'array',bookType:'xlsx'}),name:base+'.xlsx',type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}];}if(files.length!==2)throw Error('اختر ملفين للمقارنة.');const b=await extractText(files[1]);const report=texts.concat(b).every(t=>!t.trim())?'لا توجد نصوص قابلة للاستخراج. المقارنة النصية لا تكشف فروق الصور.':Array.from({length:Math.max(texts.length,b.length)},(_,i)=>texts[i]===b[i]?`صفحة ${i+1}: النص متطابق`:`صفحة ${i+1}: النص مختلف\nالملف الأول:\n${texts[i]??'صفحة غير موجودة'}\nالملف الثاني:\n${b[i]??'صفحة غير موجودة'}`).join('\n\n');return[{data:report,name:'BDF-Egypt-comparison.txt',type:'text/plain;charset=utf-8',preview:report}];}
if(['compress','grayscale','redact'].includes(id)){if(id==='redact'){const v=await readVisual(files[0]);const count=v.numPages;await v.destroy();if(Number(o.page)<1||Number(o.page)>count)throw Error('رقم الصفحة غير موجود.');}const d=await rasterPdf(files[0],{...o,grayscale:id==='grayscale'},progress,id==='redact');return pdfResult(d,base+'-'+id+'.pdf');}
if(['pdf-images','pdf-ppt'].includes(id)){const d=await readVisual(files[0]);try{const z=new JSZip();let ppt;if(id==='pdf-ppt'){const {default:PptxGenJS}=await import('pptxgenjs');ppt=new PptxGenJS();ppt.layout='LAYOUT_WIDE';}for(let i=0;i<d.numPages;i++){progress(Math.round(i/d.numPages*90));const c=await renderPage(d,i,Number(o.scale||1.5));if(ppt){const ratio=Math.min(13.333/c.width,7.5/c.height);ppt.addSlide().addImage({data:c.toDataURL('image/jpeg',.9),x:(13.333-c.width*ratio)/2,y:(7.5-c.height*ratio)/2,w:c.width*ratio,h:c.height*ratio});}else z.file(`page-${i+1}.${o.format==='png'?'png':'jpg'}`,await canvasBlob(c,o.format==='png'?'image/png':'image/jpeg',.9));}return ppt?[{data:await ppt.write({outputType:'blob'}),name:base+'.pptx',type:'application/vnd.openxmlformats-officedocument.presentationml.presentation'}]:[{data:await z.generateAsync({type:'uint8array'}),name:base+'-pages.zip',type:'application/zip'}];}finally{await d.destroy();}}
if(id==='ocr'){const {createWorker}=await import('tesseract.js');let worker;try{worker=await createWorker(o.language||'ara+eng',1,{workerPath:'/ocr/worker.min.js',corePath:'/ocr/core',langPath:'/ocr/lang',logger:m=>{if(m.status==='recognizing text')progress(Math.round(m.progress*90));}});const results=[];for(const f of files){if(f.name.toLowerCase().endsWith('.pdf')){const d=await readVisual(f);try{for(let i=0;i<d.numPages;i++){const c=await renderPage(d,i,2);results.push(`صفحة ${i+1}\n${(await worker.recognize(c)).data.text}`);}}finally{await d.destroy();}}else results.push((await worker.recognize(f)).data.text);}return[{data:results.join('\n\n'),name:base+'-ocr.txt',type:'text/plain;charset=utf-8',preview:results.join('\n\n')}];}finally{if(worker)await worker.terminate();}}
let doc=await loadPdf(files[0]);const total=doc.getPageCount();
if(['extract','organize','remove','split'].includes(id)){const indices=pageRange(o.pages||'',total,{duplicates:id==='organize'});if(id==='split'&&o.mode==='each'){const zip=new JSZip();for(const i of indices)zip.file(`page-${i+1}.pdf`,await(await selectPages(doc,[i])).save());return[{data:await zip.generateAsync({type:'uint8array'}),name:base+'-split.zip',type:'application/zip'}];}if(id==='remove'){if(!o.pages.trim())throw Error('حدد الصفحات اللي عايز تحذفها.');const keep=doc.getPageIndices().filter(i=>!indices.includes(i));if(!keep.length)throw Error('لا يمكن حذف جميع الصفحات.');doc=await selectPages(doc,keep);}else doc=await selectPages(doc,indices);}
if(id==='rotate')rotatePages(doc,o.rotation||90,pageRange(o.pages||'',total));
if(id==='numbers')await numberPages(doc,o.position,Number(o.start||1));
if(id==='watermark'){if(!o.text.trim())throw Error('اكتب نص العلامة المائية.');await stampText(doc,o.text,{opacity:Number(o.opacity||.25)});}
if(id==='crop'){const margin=Number(o.margin||20);for(const p of doc.getPages()){if(margin*2>=Math.min(p.getWidth(),p.getHeight()))throw Error('قيمة القص أكبر من مساحة الصفحة.');p.setCropBox(margin,margin,p.getWidth()-2*margin,p.getHeight()-2*margin);}}
if(['edit','sign'].includes(id)){const pi=Number(o.page||1)-1;if(pi<0||pi>=total)throw Error('رقم الصفحة غير موجود.');const p=doc.getPage(pi);let blob;if(id==='sign'){if(!signature)throw Error('ارسم التوقيع أولًا.');blob=signature;}else if(o.overlay)blob=o.overlay;else{if(!o.text.trim())throw Error('اكتب النص أو اختر صورة.');const c=document.createElement('canvas');c.width=1600;c.height=160;const ctx=c.getContext('2d');ctx.font='64px Arial';ctx.direction='rtl';ctx.textAlign='right';ctx.fillStyle=o.color||'#111111';ctx.fillText(o.text,1560,100);blob=await canvasBlob(c,'image/png');}const bm=await createImageBitmap(blob);const c=document.createElement('canvas');c.width=bm.width;c.height=bm.height;c.getContext('2d').drawImage(bm,0,0);bm.close();const im=await doc.embedPng(await(await canvasBlob(c,'image/png')).arrayBuffer());const w=p.getWidth()*Number(o.width||40)/100,h=w*im.height/im.width;p.drawImage(im,{x:p.getWidth()*Number(o.x||10)/100,y:p.getHeight()*(1-Number(o.y||75)/100)-h,width:w,height:h});}
if(id==='forms'){const form=doc.getForm();for(const f of form.getFields()){const value=o['field:'+f.getName()];if(value===undefined)continue;try{if(f.setText)f.setText(value);else if(f.check)value==='yes'?f.check():f.uncheck();else if(f.select)f.select(value);}catch{throw Error('تعذر تعديل الحقل '+f.getName()+'. قد لا يدعم النص العربي؛ جرّب إضافة نص فوق الصفحة.');}}form.updateFieldAppearances();}
if(id==='flatten')doc.getForm().flatten();
if(id==='metadata'){doc.setTitle(o.title||'');doc.setAuthor(o.author||'');doc.setSubject(o.subject||'');doc.setKeywords((o.keywords||'').split(','));}
return pdfResult(doc,base+'-'+id+'.pdf');
}
export const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export async function advanced(action,file,o){
 if(file.size>2.8*1024*1024)throw Error('حد الخدمة المتقدمة 2.8 MB.');
 let content;const isAI=['summarize','translate'].includes(action);
 if(isAI){content=(await extractText(file)).join('\n\n');if(!content.trim())throw Error('الملف مصوّر. استخرج النص باستخدام OCR أولًا.');if(content.length>60000)throw Error('الحد الحالي 60 ألف حرف لكل عملية.');}
 else{const b=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<b.length;i+=8192)raw+=String.fromCharCode(...b.subarray(i,i+8192));content=btoa(raw);}
 const response=await fetch('/api/advanced',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(o.membershipToken||'')},body:JSON.stringify({action,content,language:o.language||'Arabic'})});const data=await response.json().catch(()=>({error:'خدمة المعالجة غير متاحة.'}));if(!response.ok)throw Error(data.error||'فشلت العملية.');
 return isAI?[{data:data.text,name:'BDF-Egypt-'+action+'.txt',type:'text/plain;charset=utf-8',preview:data.text}]:[{data:Uint8Array.from(atob(data.file),c=>c.charCodeAt(0)),name:'BDF-Egypt-'+action+'.pdf',type:'application/pdf'}];
}
