const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plans=[{months:1,price:19},{months:3,price:49},{months:6,price:89},{months:12,price:149}];
let membership=null,token='',config={ready:false,whatsapp:''},show,notify;
export const batchIds=['compress','rotate','watermark','numbers','grayscale','text'];
export function hasPremium(){return !!membership && membership.expires*1000>Date.now();}
export function membershipToken(){return hasPremium()?token:'';}
const readToken=()=>{try{return JSON.parse(localStorage.getItem('bdf:membership'))||'';}catch{return '';}};
const saveToken=value=>{try{localStorage.setItem('bdf:membership',JSON.stringify(value));}catch{}};
async function request(data,admin){const res=await fetch('/api/subscription',{method:'POST',headers:{'Content-Type':'application/json',...(admin?{Authorization:'Bearer '+admin}:{})},body:JSON.stringify(data)});const result=await res.json();if(!res.ok){const error=Error(result.error||'تعذر إكمال الطلب.');error.status=res.status;throw error;}return result;}
export async function initSubscriptions(modal,toast){show=modal;notify=toast;document.querySelector('#pricing').onclick=()=>openPricing();try{const response=await fetch('/api/subscription');if(response.ok)config=await response.json();}catch{}const saved=readToken();if(saved)try{const result=await request({action:'verify',token:saved});token=saved;membership=result.membership;}catch(error){if(error.status===400)saveToken('');}updateBadge();if(location.pathname==='/pricing')openPricing(false);if(location.pathname==='/admin')openAdmin();}
function updateBadge(){document.querySelector('#pricing').textContent=hasPremium()?'اشتراكي Pro':'الباقات · من ١٩ ج';}
export function premiumOptions(id){return `<div class="pro-options"><strong>إضافات Pro</strong>${hasPremium()?`${batchIds.includes(id)?'<label class="batch-toggle"><input type="checkbox" id="batch-mode" name="batchMode"> معالجة عدة ملفات بنفس الإعدادات</label>':''}<div class="preset-actions"><button type="button" class="text-button" id="save-preset">حفظ الإعدادات</button><button type="button" class="text-button" id="load-preset">استعادة الإعدادات</button></div>`:'<p>معالجة بالدفعات وحفظ الإعدادات المفضلة.</p><button type="button" class="text-button" id="show-plans">عرض الباقات</button>'}</div>`;}
export function bindPremium(id,storage,onBatchChange){document.querySelector('#show-plans')?.addEventListener('click',()=>openPricing());document.querySelector('#batch-mode')?.addEventListener('change',onBatchChange);document.querySelector('#save-preset')?.addEventListener('click',()=>{if(!hasPremium())return notify('انتهت صلاحية الاشتراك.');const values={};document.querySelectorAll('#options input,#options select,#options textarea').forEach(el=>{if(!el.name||el.type==='file'||el.type==='password'||el.name==='batchMode')return;values[el.name]=el.type==='checkbox'?el.checked:el.value;});storage.set('bdf:preset:'+id,values);notify('تم حفظ الإعدادات على جهازك.');});document.querySelector('#load-preset')?.addEventListener('click',()=>{if(!hasPremium())return notify('انتهت صلاحية الاشتراك.');const values=storage.get('bdf:preset:'+id,null);if(!values)return notify('لسه مفيش إعدادات محفوظة لهذه الأداة.');document.querySelectorAll('#options input,#options select,#options textarea').forEach(el=>{if(Object.hasOwn(values,el.name)){if(el.type==='checkbox')el.checked=values[el.name];else el.value=values[el.name];}});notify('تمت استعادة الإعدادات.');});}
export function openPricing(push=true){if(push)history.pushState({},'', '/pricing');show('باقات بسيطة. شغل أسرع.',`<p class="pricing-lead">الأدوات الأساسية مجانية، بدون تسجيل. اختار Pro لو بتشتغل على ملفات كتير.</p><div class="plan-grid">${plans.map(p=>`<article class="plan-card ${p.months===12?'recommended':''}"><span>${p.months===1?'شهر واحد':p.months+' شهور'}</span><h3>${p.price}<small>جنيه</small></h3><p>${(p.price/p.months).toFixed(2)} ج / شهر تقريبًا</p><button class="primary" data-plan="${p.months}">طلب الاشتراك</button><small>دفعة واحدة · بدون تجديد تلقائي</small></article>`).join('')}</div><div class="plan-details"><div><h3>المجاني</h3><p>الدمج والتقسيم والتحويلات الأساسية والتوقيع وOCR المحلي والحماية. حتى 40 ملفًا و100 MB محليًا، حسب الأداة.</p></div><div><h3>Pro</h3><p>معالجة دفعات للضغط والتدوير والعلامة المائية والترقيم والتدرج الرمادي واستخراج النص. حفظ واستعادة الإعدادات لكل أداة.</p><p class="notice">التلخيص والترجمة وPDF/A وPDF القابل للبحث تحتاج خدمات إضافية؛ لا تدخل في المزايا المتاحة الآن. ستظهر عند تفعيل الخدمة.</p></div></div><p>تأكيد الدفع يدوي على واتساب، ثم تستلم كودًا ينتهي بعد مدة الباقة من تاريخ إصداره. احفظ الكود لاستعادته على جهازك. لا توجد حسابات مستخدمين أو تجديد تلقائي.</p>${hasPremium()?`<div class="membership-status">اشتراك Pro فعال حتى ${new Date(membership.expires*1000).toLocaleDateString('ar-EG')}<button id="deactivate" class="text-button">إزالة الكود من الجهاز</button></div>`:''}<form id="activate-form" class="activation-form"><label for="activation-code">عندك كود اشتراك؟</label><textarea id="activation-code" required placeholder="الصق كود التفعيل هنا" dir="ltr" autocomplete="off"></textarea><button class="primary" type="submit">تفعيل الاشتراك</button><p id="activation-message" role="status"></p></form>`);
 document.querySelectorAll('[data-plan]').forEach(el=>el.onclick=()=>checkout(plans.find(p=>p.months===Number(el.dataset.plan))));
 document.querySelector('#deactivate')?.addEventListener('click',()=>{token='';membership=null;saveToken('');updateBadge();openPricing(false);});
 document.querySelector('#activate-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;const message=document.querySelector('#activation-message');try{const value=document.querySelector('#activation-code').value.trim();const result=await request({action:'verify',token:value});membership=result.membership;token=value;saveToken(value);updateBadge();message.textContent='تم التفعيل! أغلق الباقات وافتح الأداة للاستفادة من Pro.';}catch(error){message.textContent=error.message;}finally{button.disabled=false;}};
 document.querySelector('.info-modal')?.classList.add('pricing-modal');
}
function checkout(plan){const message=`طلب اشتراك BDF Egypt Pro\nالمدة: ${plan.months} شهر\nالسعر: ${plan.price} جنيه مصري\nأرجو إرسال طريقة الدفع وتأكيد تفعيل الاشتراك بعد الاستلام.`;show('طلب الاشتراك',`<p>باقة ${plan.months} شهر — <strong>${plan.price} جنيه</strong> دفعة واحدة.</p><p>هذا طلب فقط؛ الموقع لا يخصم أي مبلغ. اتفق على وسيلة الدفع مع الإدارة وانتظر كود التفعيل بعد تأكيد الاستلام.</p>${config.ready&&config.whatsapp?`<a class="primary" target="_blank" rel="noopener noreferrer" href="https://wa.me/${config.whatsapp}?text=${encodeURIComponent(message)}">فتح الطلب على واتساب</a>`:'<p class="notice">استقبال الاشتراكات لم يُفتح بعد. رقم واتساب الإدارة قيد الإعداد؛ لا تدفع قبل ظهور وسيلة التواصل الرسمية.</p>'}<label for="order-text">تفاصيل الطلب</label><textarea id="order-text" readonly rows="6">${escape(message)}</textarea><button class="text-button" id="copy-order">نسخ الطلب</button><button class="text-button" id="back-plans">العودة للباقات</button>`);document.querySelector('#copy-order').onclick=async()=>{try{await navigator.clipboard.writeText(message);notify('تم نسخ الطلب.');}catch{document.querySelector('#order-text').select();notify('حدّدنا النص؛ انسخه من جهازك.');}};document.querySelector('#back-plans').onclick=()=>openPricing(false);}
export function openAdmin(){show('إدارة الاشتراكات',`<p>أصدر كودًا فقط بعد مراجعة الدفع يدويًا. مدة الاشتراك تبدأ الآن، ولا يحتفظ الموقع بسجل دفعات؛ احتفظ بسجل مرجع العملية والكود في مكان آمن.</p><form id="issue-form" class="activation-form"><label for="admin-secret">مفتاح الإدارة</label><input id="admin-secret" type="password" required autocomplete="off"><label for="admin-plan">الباقة</label><select id="admin-plan">${plans.map(p=>`<option value="${p.months}">${p.months} شهر — ${p.price} ج</option>`).join('')}</select><label for="payment-ref">مرجع عملية الدفع</label><input id="payment-ref" minlength="3" maxlength="100" required placeholder="رقم العملية أو المرجع في سجلك"><label for="amount-paid">المبلغ المستلم بالجنيه</label><input id="amount-paid" type="number" min="1" required><label class="batch-toggle"><input type="checkbox" id="confirmed-payment" required> راجعت واستلمت المبلغ بالفعل</label><button type="submit" class="primary">إصدار كود الاشتراك</button><p id="issue-message" role="status"></p><textarea id="issued-code" readonly hidden dir="ltr"></textarea><button type="button" id="copy-code" class="text-button" hidden>نسخ الكود</button></form>`);document.querySelector('#issue-form').onsubmit=async event=>{event.preventDefault();const btn=event.submitter;btn.disabled=true;const message=document.querySelector('#issue-message');document.querySelector('#issued-code').hidden=true;document.querySelector('#copy-code').hidden=true;try{const result=await request({action:'issue',months:Number(document.querySelector('#admin-plan').value),paid:Number(document.querySelector('#amount-paid').value),reference:document.querySelector('#payment-ref').value,confirmed:document.querySelector('#confirmed-payment').checked},document.querySelector('#admin-secret').value);document.querySelector('#issued-code').value=result.token;document.querySelector('#issued-code').hidden=false;document.querySelector('#copy-code').hidden=false;message.textContent='صدر الكود؛ ينتهي في '+new Date(result.membership.expires*1000).toLocaleDateString('ar-EG');}catch(error){message.textContent=error.message;}finally{btn.disabled=false;}};document.querySelector('#copy-code').onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector('#issued-code').value);notify('تم نسخ الكود.');}catch{document.querySelector('#issued-code').select();}};}
